### PR TITLE
Milestone: Solo Project

### PR DESCRIPTION
**Pull request by shubhsk88**
## Apple Website Copy

This PR address the submission of the solo project

- Used Grids to build the layout
- Uses the font-awesome 
- Use the float property to adjust the footer

### CODE REVIEW

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello! Great work on your project the layout is perfect!! 👍 

However there are a few changes that need to be made.

## Changes required 

- [ ] There are some repeated rules on your CSS remember to keep your code DRY (Don't repeat yourself) For example `display: flex;` is used 8 times. Lets clean up your CSS of all repeated rules. You can read this article for further information: https://speckyboy.com/good-bad-css-practices/

- [ ] Be sure to use semantic HTML there is no `main` . `header` or `footer` tags on your HTML (only the footer is mandatory)

## Optional changes

- [ ] Your navigation bar does not change color when hovering over the links, (they should turn to a darker scale of grey) [This change is optional] 

After making the requested changes please resubmit your project for review.

Cheers! 🥇

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @shubhsk88, you have done a great job 👍 You did great implementing the changes pointed out by the previous TSE 🙂  However, we left out the point he raised about applying the DRY rule. When we look into our CSS file, we can do some refactoring. For example, when we have more than 2 properties like display: flex or color: red, we could do something like this ```.class1, class2, class3, class4 { display:flex }, .class1, class2 { color:red } ```. This is an example not specific to the project

[OPTIONAL]
* Let us increase the width of the page so it looks like the original. Also, add a hover effect to the nav list items

Kindly make these changes and submit another code review 😃 
_Happy coding_ 👨‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by SofiBretz** [comment]
Well done @shubhsk88! 👏

**Project Approved!**
You did all the changes required previously. 
Good Luck with your next project. Happy coding!

**You can merge** 👍
SofiBretz.

**Pull request merged**
